spring:
  profiles:
    active: dev
  boot:
    admin:
      client:
        instance:
          name: shaoxing

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  config: classpath:logback-spring.xml

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params:
