spring:
  profiles:
    active: dev


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  config: classpath:logback-spring.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: