spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shaoxing?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: ''
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 0
    timeout: 10000
server:
  port: "@port@"
  #从pom中取出port号

file:
  content: "D:\\shaoxing\\famous_content\\"

systemParam:
  user:
    name_min_length: 6
    password_length: 32
    imagefile:
      path: "D:\\shaoxing\\image\\"
      max_name: 80


multipart:
  maxFileSize: 5242880
  maxRequestSize: 5242880
